### PR TITLE
Parts 1 and 2 of the DDD series ready for review

### PR DESCRIPTION
**Pull request by peholmst**

### CODE REVIEW

**Comment by alejandro-du** [comment]
@peholmst, thanks for the contribution. I made some fixes to the articles. However, we cannot merge this before you send the PR using the structure described at https://github.com/vaadin-learning-center/learning-content/blob/development/readme.md. Please take a look at it and let me know if you have any questions.

**Comment by peholmst** [comment]
What is wrong with the directory structure? This is not a tutorial so I don't think it should go into the tutorials directory. I can add the missing metadata files.

**Comment by alejandro-du** [comment]
This repository is used to generate the content at vaadin.com/tutorials. This is done by an automated task that requires the articles to follow the directory structure.

**Comment by peholmst** [comment]
@alejandro-du I have now changed the directory structure. I have not added any icons because I don't know what icons are available. Can you please check if something else is still missing?

**Pull request merged**
